递归：函数自己调用自己

递归如果没有任何东西拦截的话，就默认成为一个死循环

```python
def func():  
    if 123==1:  
        return   
	func()  
  
func()
```
return就可以作为break
每次执行到func的时候就会套一个局部作用域
![[Pasted image 20230919001943.png]]
这样下去内存就直接爆了
python这个时候默认有递归深度的限制，默认最大递归深度是1000
实际上永远到不了1000，这个非常大，所以算法一定有问题
```python
import sys  
  
print(sys.getrecursionlimit()) # 1000
```
![[Pasted image 20230919002252.png]]
这就是递归报错

